baseURL = 'https://udsfindshappiness.com/'
languageCode = 'en-us'
title = 'Uds Finds Happiness'
theme = 'ananke'
[params]
  imageCdn = 'https://udsfindshappinesscontent.nyc3.cdn.digitaloceanspaces.com/homepage'
  read_more_copy = "Read more..."
[caches]
  [caches.images]
    dir = ':cacheDir/images'